name: 'TGAT'
dropout: 0.1
att_head: 2
att_dropout: 0.1
num_layers: 2
fanouts: [10, 10]
sample_strategy: "uniform"
num_snapshots: 1
snapshot_time_window: 0
prop_time: False
use_memory: False
dim_time: 100
dim_embed: 100