name: 'TGN'
dropout: 0.2
att_head: 2
att_dropout: 0.2
num_layers: 1
fanouts: [10]
sample_strategy: "recent"
num_snapshots: 1
snapshot_time_window: 0
prop_time: False
use_memory: True
dim_time: 100
dim_embed: 100
dim_memory: 100