name: "MAG"
ingestion_window: '1M'
timestamp_unit: 'M'
batch_size: 1024
task: "node_classification"
num_nodes: 121751665
num_edges: 1297748926
node_feat_dim: 768
edge_feat_dim: 0
num_classes: 2
test_ratio: 0.2
num_epochs: 20
data:
    initial_pool_size: 5
    maximum_pool_size: 200
    minimum_block_size: 8
    mem_resource_type: "pinned"
    blocks_to_preallocate: 65536
cache:
    name: 'lru'
    node_cache_ratio: 0.01
    edge_cache_ratio: 0