name: "tgbn_genre"
ingestion_window: '1d'
timestamp_unit: 's'
batch_size: 2000
task: 'node_classification'
eval_metric: "ndcg"
num_nodes: 1505
num_edges: 17858395
num_classes: 513
node_feat_dim: 100 
edge_feat_dim: 1
test_ratio: 0.2
num_epochs: 20
finetune_num_epochs: 1
initial_offline_ratio: 0.1
slo_threshold: 0.5
offline_ratio: 0.3
data:
    initial_pool_size: 1
    maximum_pool_size: 4
    minimum_block_size: 32
    mem_resource_type: "cuda"
    blocks_to_preallocate: 1024
cache:
    name: 'lru'
    node_cache_ratio: 1
    edge_cache_ratio: 0.55
